### ISSUE TITLE
LUA errors on game world load

### ISSUE THREAD

**Issue by towneh** [rgd87/ClassicAuraDurations#1]
Message: Error loading Interface\AddOns\ClassicAuraDurations\Libs\LibStub\LibStub.lua
Time: Thu Jun  6 20:24:49 2019
Count: 3

---

Message: Error loading Interface\AddOns\ClassicAuraDurations\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua
Time: Thu Jun  6 20:24:49 2019
Count: 3

---

Message: Couldn't open Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\LibClassicDurations.xml
Time: Thu Jun  6 20:24:49 2019
Count: 3

---

Message: Interface\AddOns\ClassicAuraDurations\code.lua:6: Cannot find a library instance of "LibClassicDurations".
Time: Thu Jun  6 20:24:51 2019
Count: 1
Stack: Interface\AddOns\ClassicAuraDurations\code.lua:6: Cannot find a library instance of "LibClassicDurations".
[C]: in function `error'
...Ons\ClassicCastbars_Options\Libs\LibStub\LibStub.lua:23: in function `LibStub'
Interface\AddOns\ClassicAuraDurations\code.lua:6: in function <Interface\AddOns\ClassicAuraDurations\code.lua:5>

Locals: (*temporary) = "Cannot find a library instance of "LibClassicDurations"."

**Comment by d87** [comment]
don't install the github repo archive, it doesn't have the external libs. Download from here https://github.com/rgd87/ClassicAuraDurations/releases
