### ISSUE TITLE
Wrong spellIDs for Improved Blizzard?

### ISSUE THREAD

**Issue by Kraily** [rgd87/ClassicAuraDurations#10]
Just wondered, why this addon is not working with improved blizzard. I think there are the wrong spellIDs.

Line 611 in LibAuraTypes:
`A({ 12484, 12485, 12486 }, { type = SLOW }) -- Improved Blizzard`

Correct IDs for Improved Blizzard should be [11185](https://classic.wowhead.com/spell=11185), [12487](https://classic.wowhead.com/spell=12487) and [12488](https://classic.wowhead.com/spell=12488).

I wasn't able to test it yet, but it should work with this line:
`A({ 11185, 12487, 12488 }, { type = SLOW }) -- Improved Blizzard`

Best regards!

**Comment by d87** [comment]
If by not working you mean not showing timers then it has nothing to do with LibAuraTypes, which is used to classify spells to show inside portrait frame.
But Imp Blizzard just doesn't work, it's not in combat log. The ids you posted are talent spell ids, not aura ids

**Comment by Kraily** [comment]
Thanks for clarification, then there is no way to show the timers?

**Comment by d87** [comment]
Well, while AURA_APPLIED event is missing, it's possible to use damage events. I'll try that some time

**Comment by Kraily** [comment]
Would be awesome! I'll close this issue for now!
