### ISSUE TITLE
Deadly Poison not refreshing at 5 Stacks

### ISSUE THREAD

**Issue by OMEGALULW** [rgd87/ClassicAuraDurations#14]
Deadly Poison refeshes just fine until you hit 5 stacks, then it just stops

**Comment by d87** [comment]
Yeah, that's a known combat log issue. Can't be fixed

**Comment by OMEGALULW** [comment]
It can't be worked around by comparing # of charges when stacks are known to be at 5? Either way, hopefully Blizz can fix this

**Comment by d87** [comment]
Maybe it's possible, but'll be very complicated and not worth the trouble. Other things like winter's chill have workarounds.
Blizzard haven't fixed it since cataclysm, so it's unlikely they're going to start now, and even more unlikely it'll trickle down to classic

**Comment by OMEGALULW** [comment]
Fair enough. If it could be worked around it still wouldn't work in BC or Wrath Classic since they got rid of poison charges in BC so it would indeed not be worth the trouble lol
