### ISSUE TITLE
LUA errors when being attacked by enemy faction

### ISSUE THREAD

**Issue by towneh** [rgd87/ClassicAuraDurations#2]
Message: ...assicAuraDurations\Libs\LibClassicDurations\core.lua:194: attempt to perform arithmetic on local 'mul' (a nil value)
Time: Fri Jun  7 18:22:45 2019
Count: 4
Stack: ...assicAuraDurations\Libs\LibClassicDurations\core.lua:194: attempt to perform arithmetic on local 'mul' (a nil value)
...assicAuraDurations\Libs\LibClassicDurations\core.lua:194: in function <...assicAuraDurations\Libs\LibClassicDurations\core.lua:147>
...assicAuraDurations\Libs\LibClassicDurations\core.lua:220: in function <...assicAuraDurations\Libs\LibClassicDurations\core.lua:206>
(tail call): ?

Locals: srcGUID = "Player-4619-00014B5D"
dstGUID = "Pet-0-4615-0-4279-416-090000A866"
dstName = "Jakpad"
dstFlags = 4424
spellID = 5246
spellName = "Intimidating Shout"
opts = <table> {
 duration = 8
}
auraType = "DEBUFF"
doRemove = nil
guidTable = <table> {
 5246 = <table> {
 }
}
isStacking = nil
spellTable = <table> {
}
applicationTable = <table> {
}
duration = 8
mul = nil
(*temporary) = "Pet-0-4615-0-4279-416-090000A866"
(*temporary) = 5246
(*temporary) = "attempt to perform arithmetic on local 'mul' (a nil value)"
guids = <table> {
 Player-4619-0000DEDE = <table> {
 }
 Creature-0-4615-0-4276-587-00007A5C9E = <table> {
 }
 Creature-0-4615-0-4276-1096-00007A2D08 = <table> {
 }
 Creature-0-4615-189-6881-4295-00017A5143 = <table> {
 }
 Creature-0-4615-0-4276-684-00007A2C76 = <table> {
 }
 Creature-0-4615-0-4276-697-00007A6039 = <table> {
 }
 Creature-0-4615-189-6846-4540-00017A457A = <table> {
 }
 Creature-0-4615-189-6881-4298-00017A5144 = <table> {
 }
 Creature-0-4615-0-4276-1096-00007A2930 = <table> {
 }
 Creature-0-4615-70-7122-4861-00027A9080 = <table> {
 }
 Creature-0-4615-0-4271-4285-00007A4AAB = <table> {
 }
 Creature-0-4615-189-6846-4540-00017A457C = <table> {
 }
 Creature-0-4615-0-4279-4846-0000FA3C0E = <table> {
 }
 Creature-0-4615-0-4276-1142-00007A27CD = <table> {
 }
 Creature-0-4615-0-4276-587-00007A637A = <table> {
 }
 Creature-0-4615-0-4276-1142-00007A2A87 = <table> {
 }
 Creature-0-4615-0-4276-697-00007A35A4 = <table> {
 }
 Creature-0-4615-0-4276-681-00007A379E = <table> {
 }
 Creature-0-4615-0-4276-1142-00007A29B2 = <table> {
 }
 Creature-0-4615-189-6846-4287-00037A457B = <table> {
 }
 Creature-0-4615-0-4276-1096-00007A2A0A = <table> {
 }
 Creature-0-4615-0-4276-686-0000FA5E5E = <table> {
 }
 Creature-0-4615-0-4276-684-00007A2D03 = <table> {
 }
 Creature-0-4615-189-6824-4301-0003FA3D5B = <table> {
 }
 Creature-0-4615-189-6846-4298-00007A457A = <table> {
 }
 Creature-0-4615-0-4279-2735-00007A8237 = <table> {
 }
 Player-4619-0000C418 = <table> {
 }
 Creature-0-4615-0-4276-684-00007A2D76 = <table> {
 }
 Creature-0-4615-189-6824-4300-00007A3D5D = <table> {
 }
 Creature-0-4615-0-4276-1096-00007A2BB6 = <table> {
 }
 Creature-0-4615-0-4276-1096-00007A2A39 = <table> {
 }
 Creature-0-4615-0-4276-697-00007A661B = <table> {
 }
 Creature-0-4615-0-4276-1144-00007A28DC = <table> {
 }
 Pet-0-4615-0-4279-416-090000A866 = <table> {
 }
 Player-4619-0008090B = <table> {
 }
 Creature-0-4615-189-6881-4299-00037A5144 = <table> {
 }
 Creature-0-4615-70-7122-4861-00017A9080 = <table> {
 }
 Creature-0-4615-0-4276-694-00007A63C9 = <table> {
 }
 Creature-0-4615-0-4276-772-00007A2D66 = <table> {
 }
 Creature-0-4615-189-6846-4301-00007A457B = <table> {
 }
 Player-4619-0000D449 = <table> {
 }
 Creature-0-4615-189-6846-4300-00027A457C = <table> {
 }
 Player-4619-0000D799 = <table> {
 }
 Player-4619-00015892 = <table> {
 }
 Creature-0-4615-0-4276-690-00007A70CA = <table> {
 }
 Creature-0-4615-70-7122-4853-00027A9080 = <table> {
 }
 Creature-0-4615-189-6881-4300-00007A5144 = <table> {
 }
 Creature-0-4615-0-4276-690-00007A62AA = <table> {
 }
 Creature-0-4615-0-4276-689-00007A5FFA = <table> {
 }
 Creature-0-4615-70-7122-7321-00007A9081 = <table> {
 }
 Creature-0-4615-0-4276-689-00007A6043 = <table> {
 }
 Creature-0-4615-189-6881-4540-00077A5144 = <table> {
 }
 Player-4619-000C513A = <table> {
 }
 Creature-0-4615-70-7122-7320-0000FA9081 = <table> {
 }
 Creature-0-4615-70-712

---

Message: ...assicAuraDurations\Libs\LibClassicDurations\core.lua:257: attempt to compare number with nil
Time: Fri Jun  7 18:22:44 2019
Count: 2
Stack: ...assicAuraDurations\Libs\LibClassicDurations\core.lua:257: attempt to compare number with nil
...assicAuraDurations\Libs\LibClassicDurations\core.lua:257: in function <...assicAuraDurations\Libs\LibClassicDurations\core.lua:239>
(tail call): ?
Interface\AddOns\ClassicAuraDurations\code.lua:89: in function <Interface\AddOns\ClassicAuraDurations\code.lua:81>
[C]: in function `CompactUnitFrame_UtilSetDebuff'
Interface\FrameXML\CompactUnitFrame.lua:949: in function `CompactUnitFrame_UpdateDebuffs'
Interface\FrameXML\CompactUnitFrame.lua:553: in function `CompactUnitFrame_UpdateAuras'
Interface\FrameXML\CompactUnitFrame.lua:98: in function <Interface\FrameXML\CompactUnitFrame.lua:51>

Locals: dstGUID = "Player-4619-00014B5D"
spellID = 6213
srcGUID = "Player-4619-0000BE01"
isStacking = nil
guidTable = <table> {
 6213 = <table> {
 }
 7648 = <table> {
 }
 2941 = <table> {
 }
 589 = <table> {
 }
 8492 = <table> {
 }
 8053 = <table> {
 }
}
spellTable = <table> {
}
applicationTable = <table> {
}
duration = nil
expirationTime = nil
(*temporary) = 149219.409000
(*temporary) = 149219.409000
(*temporary) = "attempt to compare number with nil"
guids = <table> {
 Player-4619-0000DEDE = <table> {
 }
 Creature-0-4615-0-4276-587-00007A5C9E = <table> {
 }
 Creature-0-4615-0-4276-1096-00007A2D08 = <table> {
 }
 Creature-0-4615-189-6881-4295-00017A5143 = <table> {
 }
 Creature-0-4615-0-4276-684-00007A2C76 = <table> {
 }
 Creature-0-4615-0-4276-697-00007A6039 = <table> {
 }
 Creature-0-4615-189-6846-4540-00017A457A = <table> {
 }
 Creature-0-4615-189-6881-4298-00017A5144 = <table> {
 }
 Creature-0-4615-0-4276-1096-00007A2930 = <table> {
 }
 Creature-0-4615-70-7122-4861-00027A9080 = <table> {
 }
 Creature-0-4615-0-4271-4285-00007A4AAB = <table> {
 }
 Creature-0-4615-189-6846-4540-00017A457C = <table> {
 }
 Creature-0-4615-0-4279-4846-0000FA3C0E = <table> {
 }
 Creature-0-4615-0-4276-1142-00007A27CD = <table> {
 }
 Creature-0-4615-0-4276-587-00007A637A = <table> {
 }
 Creature-0-4615-0-4276-1142-00007A2A87 = <table> {
 }
 Creature-0-4615-0-4276-697-00007A35A4 = <table> {
 }
 Creature-0-4615-0-4276-681-00007A379E = <table> {
 }
 Creature-0-4615-0-4276-1142-00007A29B2 = <table> {
 }
 Creature-0-4615-189-6846-4287-00037A457B = <table> {
 }
 Creature-0-4615-0-4276-1096-00007A2A0A = <table> {
 }
 Creature-0-4615-0-4276-686-0000FA5E5E = <table> {
 }
 Creature-0-4615-0-4276-684-00007A2D03 = <table> {
 }
 Creature-0-4615-189-6824-4301-0003FA3D5B = <table> {
 }
 Creature-0-4615-189-6846-4298-00007A457A = <table> {
 }
 Creature-0-4615-0-4279-2735-00007A8237 = <table> {
 }
 Player-4619-0000C418 = <table> {
 }
 Creature-0-4615-0-4276-684-00007A2D76 = <table> {
 }
 Creature-0-4615-189-6824-4300-00007A3D5D = <table> {
 }
 Creature-0-4615-0-4276-1096-00007A2BB6 = <table> {
 }
 Creature-0-4615-0-4276-1096-00007A2A39 = <table> {
 }
 Creature-0-4615-0-4276-697-00007A661B = <table> {
 }
 Creature-0-4615-0-4276-1144-00007A28DC = <table> {
 }
 Player-4619-0008090B = <table> {
 }
 Creature-0-4615-189-6881-4299-00037A5144 = <table> {
 }
 Creature-0-4615-70-7122-4861-00017A9080 = <table> {
 }
 Creature-0-4615-0-4276-694-00007A63C9 = <table> {
 }
 Creature-0-4615-0-4276-772-00007A2D66 = <table> {
 }
 Creature-0-4615-189-6846-4301-00007A457B = <table> {
 }
 Player-4619-0000D449 = <table> {
 }
 Creature-0-4615-189-6846-4300-00027A457C = <table> {
 }
 Player-4619-0000D799 = <table> {
 }
 Player-4619-00015892 = <table> {
 }
 Creature-0-4615-0-4276-690-00007A70CA = <table> {
 }
 Creature-0-4615-70-7122-4853-00027A9080 = <table> {
 }
 Creature-0-4615-189-6881-4300-00007A5144 = <table> {
 }
 Creature-0-4615-0-4276-690-00007A62AA = <table> {
 }
 Creature-0-4615-0-4276-689-00007A5FFA = <table> {
 }
 Creature-0-4615-70-7122-7321-00007A9081 = <table> {
 }
 Creature-0-4615-0-4276-689-00007A6043 = <table> {
 }
 Creature-0-4615-189-6881-45

**Comment by towneh** [comment]
This was in version 1.13.2 earlier today

**Comment by d87** [comment]
that should be fixed in the most recent version (1.13.4)
