### ISSUE TITLE
Enabling Target of Target causes addon to crash

### ISSUE THREAD

**Issue by michael-f-portfolio** [rgd87/ClassicAuraDurations#3]
Version: 1.13.9
Other Addons: None
When Target of Target is enabled and a DoT is cast on an enemy or selecting a player who has another target selected, the following LUA error occurs. This results in the DoTs being incorrectly tracked, or the DoTs not showing up under the target frame at all.

When Target of Target is disabled the addon works correctly.

Message: Interface\AddOns\ClassicAuraDurations\code.lua:254: attempt to compare number with nil
Time: Thu Jun 20 13:48:19 2019
Count: 1
Stack: Interface\AddOns\ClassicAuraDurations\code.lua:254: attempt to compare number with nil
Interface\AddOns\ClassicAuraDurations\code.lua:254: in function <Interface\AddOns\ClassicAuraDurations\code.lua:57>
[C]: in function `TargetFrame_UpdateAuras'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
Interface\FrameXML\TargetFrame.lua:910: in function `TargetofTarget_Update'
Interface\FrameXML\TargetFrame.lua:420: in function `TargetFrame_OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: self = TargetFrame {
 0 = <userdata>
 debuffs = TargetFrameDebuffs {
 }
 portrait = TargetFramePortrait {
 }
 totFrame = TargetFrameToT {
 }
 raidTargetIcon = TargetFrameTextureFrameRaidTargetIcon {
 }
 highLevelTexture = TargetFrameTextureFrameHighLevelTexture {
 }
 petBattleIcon = TargetFrameTextureFramePetBattleIcon {
 }
 prestigePortrait = TargetFrameTextureFramePrestigePortrait {
 }
 showAuraCount = true
 showLeader = true
 healthbar = TargetFrameHealthBar {
 }
 pvpIcon = TargetFrameTextureFramePVPIcon {
 }
 buffsOnTop = false
 questIcon = TargetFrameTextureFrameQuestIcon {
 }
 deadText = TargetFrameTextureFrameDeadText {
 }
 noTextPrefix = true
 buffs = TargetFrameBuffs {
 }
 nameBackground = TargetFrameNameBackground {
 }
 showLevel = true
 levelText = TargetFrameTextureFrameLevelText {
 }
 leaderIcon = TargetFrameTextureFrameLeaderIcon {
 }
 statusSign = -1
 unit = "target"
 showPVP = true
 borderTexture = TargetFrameTextureFrameTexture {
 }
 showPortrait = true
 TOT_AURA_ROW_WIDTH = 101
 statusCounter = 0
 unconsciousText = TargetFrameTextureFrameUnconsciousText {
 }
 manabar = TargetFrameManaBar {
 }
 auraRows = 0
 unitHPPercent = 1
 spellbar = TargetFrameSpellBar {
 }
 prestigeBadge = TargetFrameTextureFramePrestigeBadge {
 }
 menu = <function> defined @Interface\FrameXML\TargetFrame.lua:92
 showClassification = true
 textureFrame = TargetFrameTextureFrame {
 }
 name = TargetFrameTextureFrameName {
 }
 Background = TargetFrameBackground {
 }
}
frame = nil
frameName = nil
frameIcon = nil
frameCount = nil
frameCooldown = nil
numBuffs = 0
playerIsTarget = false
selfName = "TargetFrame"
canAssist = false
unit = "target"
maxPrio = 0
maxPrioFilter = nil
maxPrioIndex = 1
color = nil
frameBorder = nil
numDebuffs = 0
frameNum = 1
index = 1
maxDebuffs = 16
mirrorAurasVertically = false
haveTargetofTarget = true
maxRowWidth = 101
(*temporary) = 0
(*temporary) = nil
(*temporary) = "TargetFrameBuff"
(*temporary) = 0
(*temporary) = 0
(*temporary) = <table> {
 1 = true
}
(*temporary) = <function> defined @Interface\FrameXML\TargetFrame.lua:676
(*temporary) = 101
(*temporary) = 3
(*temporary) = false
(*temporary) = nil
(*temporary) = 1
(*temporary) = 0
(*temporary) = 1
(*temporary) = 0
(*temporary) = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
LibClassicDurations = <table> {
 GetAuraDurationByGUID = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:425
 buffCache = <table> {
 }
 Unregister = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:444
 Register = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:432
 callbacks = <table> {
 }
 UnitAuraDirect = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:346
 GetAuraDurationByUnit = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:417
 UnregisterFrame = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:444
 guids = <table> {
 }
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\CallbackHandler-1.0\

**Comment by d87** [comment]
ok, fixed in 1.13.11
