### ISSUE TITLE
Broken as of closed beta

### ISSUE THREAD

**Issue by Sneakyrhino1** [rgd87/ClassicAuraDurations#4]
https://gyazo.com/bb212f63db7773bd72e6a27291d3fe83 (gif of my lua errors)

**Comment by d87** [comment]
completely restart the game client

**Comment by Sneakyrhino1** [comment]
i have and the error always shows after entering world and does not go away untill you turn it off.

worth noting other addons like realmobhealth are also broken so its some api change

**Comment by d87** [comment]
No, it's either you didn't restart the game or you're doing something weird like installing github repos instead of actual releases. Because repos do not contain libraries
