### ISSUE TITLE
Compatibility with ElvUI

### ISSUE THREAD

**Issue by Segysmundo** [rgd87/ClassicAuraDurations#6]
Love this addon but unfortunately when using ElvUI, timers won't show up at all.

Do you think you could make it compatible with ElvUI so ClassicAuraDuration's timers can be displayed on ElvUI's unit frame debuffs?

Or is this something ElvUI's dev has to do?

**Comment by elonmust69** [comment]
keen to know this as well.

**Comment by d87** [comment]
I'm pretty sure ElvUI does support LibClassicDurations, CAD has nothing to do with ElvUI
