### ISSUE TITLE
Mage Issue

### ISSUE THREAD

**Issue by sheha316** [rgd87/ClassicAuraDurations#8]
hi, i get 2 issues when i play with a mage

1. The timer of the DoT of Pyroblast it doesnt work

2. The timer of the DoT of fireball works great, but if there is another mage using fireball the Timer of the DoT of both spells refresh

**Comment by sheha316** [comment]
thanks to your comments i can fix the first issue.
in classAbilities I put this : 
Spell({11366, 12505, 12522, 12523, 12524, 12525, 12526, 18809}, {duration =12}) -- Pyroblast

**Comment by d87** [comment]
latest update contains both pyroblast and fireball fixes
